import React from 'react';
import styles from './Incentive.module.css';
import highlightImage from '/assets/PNG/INCENTIVE/Images/highlight.png';
import TeamIcons from '../TeamIcons/TeamIcons';

const Incentive: React.FC = () => {
  return (
    <section className={styles.incentiveSection}>
      <div className={styles.incentiveContainer}>
        <h1>Incentive Program</h1>
        <img src={highlightImage} alt="highlight" className={styles.highlightImage} />
        <div className={styles.textContainer}>
          <p className={styles.introText}>
            The incentive program works as follows: If you refer a group, you'll earn 20% of all commissions generated by that group's profits for life.
          </p>
          <p className={styles.introText}>
            Additionally, group owners earn 20% of the profits from groups where they have the bot and hold ownership. The program is in its beginning phases, please reach out to the contacts below if you are interested in partnering.
          </p>
        </div>
        <TeamIcons />
      </div>
    </section>
  );
};

export default Incentive;
